<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <NoWarn>1701;1702;1591</NoWarn>
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <NoWarn>1701;1702;1591</NoWarn>
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NModbus4.Core" Version="1.0.2" />
    <PackageReference Include="Quartz" Version="3.6.0" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" Version="3.6.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.6.0" />
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
    <PackageReference Include="SuperSocket.ClientEngine" Version="0.10.0" />
    <PackageReference Include="SuperSocket.ProtoBase" Version="1.7.0.17" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" Version="1.5.374.54" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VgAutoDrill.Fundation.Iot\VgAutoDrill.Fundation.Iot.csproj" />
  </ItemGroup>
</Project>