<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="appsettings.std.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Polly" Version="8.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\VgAutoDrill.Central\VgAutoDrill.Central.csproj" />
    <ProjectReference Include="..\VegaIot.External.Agv\VegaIot.External.Agv.csproj" />
  </ItemGroup>
</Project>