<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="IoTClient" Version="1.0.42" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="NModbus" Version="3.0.81" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.2.3" />
    <PackageReference Include="VegaIot.External.AgvEntity" Version="3.9.3.1415" />
    <PackageReference Include="VgAutoDrill.Fundation" Version="3.9.3.1415" />
    <PackageReference Include="VgAutoDrill.Fundation.CNC" Version="3.9.3.1415" />
    <PackageReference Include="VgAutoDrill.Fundation.Iot" Version="3.9.3.1415" />
    <PackageReference Include="VgAutoDrill.Infrastructure" Version="3.9.3.1415" />
  </ItemGroup>
</Project>