<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <FileVersion>1.0.0.1</FileVersion>
    <AssemblyVersion>1.0.0.1</AssemblyVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>6</WarningLevel>
    <NoWarn>1701;1702;1591;1998;8629;1573</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>6</WarningLevel>
    <NoWarn>1701;1702;1591;1998;8629;1573</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.3.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VgAutoDrill.Admin.Model\VgAutoDrill.Admin.Model.csproj" />
    <ProjectReference Include="..\VgAutoDrill.Admin.Repository\VgAutoDrill.Admin.Repository.csproj" />
  </ItemGroup>
</Project>