<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="appsettings.kingwong.json" />
  </ItemGroup>
  <ItemGroup>

    <PackageReference Include="VgAutoDrill.Fundation" Version="3.9.3.1415" />
    <PackageReference Include="VgAutoDrill.Fundation.CNC" Version="3.9.3.1415" />
    <PackageReference Include="VgAutoDrill.Fundation.Iot" Version="3.9.3.1415" />
    <PackageReference Include="SqlSugar.IOC" Version="1.7.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.102" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.kinwong.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>