global using Masa.Blazor;
global using Microsoft.AspNetCore.Components;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Reflection;
global using System.Text.Json;
global using VgCNCServer;
global using VgCNCServer.Global;
global using VgCNCServer.Global.Nav.Model;
