version: '3.4'

services:
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    restart: always
     
  mysql:
    image: mysql:5.7.41
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - /vega/mysql/log:/var/log/mysql
      - /vega/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306" 
    restart: always

  clickhouse:
    image: bitnami/clickhouse:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes   
    volumes:
      - /vega/clickhouse/data/preprocessed_configs:/bitnami/clickhouse/data/preprocessed_configs  
    ports:
      - "8123:8123" 
    restart: always