<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>$(Version)</Version>
		<Company>$(Company)</Company>
		<Copyright>$(Copyright)</Copyright>
		<WebPage>$(WebPage)</WebPage>
		<Authors>$(Authors)</Authors>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<ApplicationIcon>logo.ico</ApplicationIcon>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <WarningLevel>6</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <WarningLevel>6</WarningLevel>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="logs\**" />
	  <Content Remove="logs\**" />
	  <EmbeddedResource Remove="logs\**" />
	  <None Remove="logs\**" />
	</ItemGroup>
	<ItemGroup>
	  <Content Remove="Components\LiftingProcessedStagingDesk.razor" />
	</ItemGroup>
	<ItemGroup>
	  <None Remove="data\1.drl" />
	  <None Remove="RunAgent.bat" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="data\1.drl">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Include="logo.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="RunAgent.bat">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="NLog.Extensions.Logging" Version="5.2.3" />
	  <PackageReference Include="NLog.Web.AspNetCore" Version="5.2.3" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\..\..\VgAutoDrill.Fundation\VgAutoDrill.Fundation.csproj" />
	  <ProjectReference Include="..\VgAutoDrill.JinLu\VgAutoDrill.JinLu.csproj" />	  
	</ItemGroup>
	<ItemGroup>
	  <Content Update="appsettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="conf\appsettings.Development.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	  <Content Update="conf\appsettings.Production.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
