<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningLevel>6</WarningLevel>
    <NoWarn>1701;1702;1591;1998;8629;1573</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <WarningLevel>6</WarningLevel>
    <NoWarn>1701;1702;1591;1998;8629;1573</NoWarn>
  </PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.13" />
  </ItemGroup>
</Project>