<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.14" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
    <PackageReference Include="SqlSugar.IOC" Version="1.7.0" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.102" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VgEAPClient.Common\VgEAPClient.Common.csproj" />
  </ItemGroup>

</Project>
