<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <NoWarn>1701;1702;1591</NoWarn>
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <NoWarn>1701;1702;1591</NoWarn>
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Models\PanelDrillState.cs" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="UnitTest.VgAutoDrill.Central" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VgAutoDrill.Fundation.Utils\VgAutoDrill.Fundation.Utils.csproj" />
  </ItemGroup>
</Project>