<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="AutoMapper\**" />
    <EmbeddedResource Remove="AutoMapper\**" />
    <None Remove="AutoMapper\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="11.0.1" />
    <PackageReference Include="Npoi.Mapper" Version="3.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VgAutoDrill.Admin.Common\VgAutoDrill.Admin.Common.csproj" />
    <ProjectReference Include="..\VgAutoDrill.Admin.Model\VgAutoDrill.Admin.Model.csproj" />
  </ItemGroup>
</Project>