<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591</NoWarn>
    <WarningLevel>6</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;1591;1572;1573;8604;8618;8603</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;1591;1572;1573;8604;8618;8603</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Core\Schedule\AgvDeviceFilter.cs" />
    <Compile Remove="Core\Schedule\Handler\ForkOrShelfExchangeSiloHandler.cs" />
    <Compile Remove="Core\Schedule\IAgvDeviceFilter.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="7.2.0" />
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="Mediator.Net.MicrosoftDependencyInjection" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.13" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="SqlSugar.IOC" Version="1.7.0" />
    <PackageReference Include="MQTTnet" Version="4.3.7.1207" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.2.3" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.2.2" />
    <PackageReference Include="SqlSugarCore" Version="5.1.4.170" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="ClickHouse.Client" Version="6.4.0" />
    <PackageReference Include="VegaIot.External.AgvEntity" Version="3.9.3.1415" />
    <PackageReference Include="VgAutoDrill.Admin.Application" Version="3.10.21.1025" />
    <PackageReference Include="VgAutoDrill.Admin.Model" Version="3.10.21.1025" />
    <PackageReference Include="VgAutoDrill.Fundation" Version="3.9.3.1415" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="UnitTest.VgAutoDrill.Central" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>
</Project>
